apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: http
      targetPort: 8080
      nodePort: 30000
    - port: jnlp
      targetPort: 50000
      nodePort: 30001
  selector:
    app: jenkins
